# Generated by Django 2.2.1 on 2019-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resumedata_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
