# Generated by Django 2.2.1 on 2019-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20190504_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='instagram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='twitter',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
