# Generated by Django 2.2.1 on 2019-05-07 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20190507_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='temp',
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
