# Generated by Django 2.2.1 on 2019-05-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20190507_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='user',
        ),
    ]
