# Generated by Django 2.2.1 on 2019-07-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20190707_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='username',
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='facebook',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='instagram',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='major3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='s_end3',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='s_start3',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='school3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='twitter',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
