# Generated by Django 2.2.1 on 2019-07-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20190714_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
